name: BookingYa CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar pruebas Java
        working-directory: BookingYa
        run: mvn clean test

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Playwright
        working-directory: BookingYa/playwright
        run: |
          npm install
          npx playwright install

      - name: Ejecutar Playwright
        working-directory: BookingYa/playwright
        run: npx playwright test
